[[redirects]]
    from="/add"
    to="/"
    status= 200
    force = true

[[redirects]]
    from="/config"
    to="/"
    status= 200
    force = true

[[redirects]]
    from="/meta/*"
    to="/"
    status= 200
    force = true

[[redirects]]
    from="/meta/*/edit"
    to="/"
    status= 200
    force = true